/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedMyPlansIndexRouteImport } from './routes/_authenticated/my-plans/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedProfileUserIdIndexRouteImport } from './routes/_authenticated/profile/$userId/index'
import { Route as AuthenticatedMyPlansPlanIdIndexRouteImport } from './routes/_authenticated/my-plans/$planId/index'
import { Route as AuthenticatedMyPlansPlanIdLayoutRouteImport } from './routes/_authenticated/my-plans/$planId/_layout'
import { Route as AuthenticatedMyPlansPlanIdLayoutPhasesIndexRouteImport } from './routes/_authenticated/my-plans/$planId/_layout/phases/index'
import { Route as AuthenticatedMyPlansPlanIdLayoutMembersIndexRouteImport } from './routes/_authenticated/my-plans/$planId/_layout/members/index'
import { Route as AuthenticatedMyPlansPlanIdLayoutDashboardIndexRouteImport } from './routes/_authenticated/my-plans/$planId/_layout/dashboard/index'
import { Route as AuthenticatedMyPlansPlanIdLayoutConfigIndexRouteImport } from './routes/_authenticated/my-plans/$planId/_layout/config/index'
import { Route as AuthenticatedMyPlansPlanIdLayoutBillsIndexRouteImport } from './routes/_authenticated/my-plans/$planId/_layout/bills/index'
import { Route as AuthenticatedMyPlansPlanIdLayoutPhasesPhaseIdIndexRouteImport } from './routes/_authenticated/my-plans/$planId/_layout/phases/$phaseId/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyPlansIndexRoute =
  AuthenticatedMyPlansIndexRouteImport.update({
    id: '/my-plans/',
    path: '/my-plans/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileUserIdIndexRoute =
  AuthenticatedProfileUserIdIndexRouteImport.update({
    id: '/profile/$userId/',
    path: '/profile/$userId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyPlansPlanIdIndexRoute =
  AuthenticatedMyPlansPlanIdIndexRouteImport.update({
    id: '/my-plans/$planId/',
    path: '/my-plans/$planId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyPlansPlanIdLayoutRoute =
  AuthenticatedMyPlansPlanIdLayoutRouteImport.update({
    id: '/my-plans/$planId/_layout',
    path: '/my-plans/$planId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyPlansPlanIdLayoutPhasesIndexRoute =
  AuthenticatedMyPlansPlanIdLayoutPhasesIndexRouteImport.update({
    id: '/phases/',
    path: '/phases/',
    getParentRoute: () => AuthenticatedMyPlansPlanIdLayoutRoute,
  } as any)
const AuthenticatedMyPlansPlanIdLayoutMembersIndexRoute =
  AuthenticatedMyPlansPlanIdLayoutMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedMyPlansPlanIdLayoutRoute,
  } as any)
const AuthenticatedMyPlansPlanIdLayoutDashboardIndexRoute =
  AuthenticatedMyPlansPlanIdLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedMyPlansPlanIdLayoutRoute,
  } as any)
const AuthenticatedMyPlansPlanIdLayoutConfigIndexRoute =
  AuthenticatedMyPlansPlanIdLayoutConfigIndexRouteImport.update({
    id: '/config/',
    path: '/config/',
    getParentRoute: () => AuthenticatedMyPlansPlanIdLayoutRoute,
  } as any)
const AuthenticatedMyPlansPlanIdLayoutBillsIndexRoute =
  AuthenticatedMyPlansPlanIdLayoutBillsIndexRouteImport.update({
    id: '/bills/',
    path: '/bills/',
    getParentRoute: () => AuthenticatedMyPlansPlanIdLayoutRoute,
  } as any)
const AuthenticatedMyPlansPlanIdLayoutPhasesPhaseIdIndexRoute =
  AuthenticatedMyPlansPlanIdLayoutPhasesPhaseIdIndexRouteImport.update({
    id: '/phases/$phaseId/',
    path: '/phases/$phaseId/',
    getParentRoute: () => AuthenticatedMyPlansPlanIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/my-plans/': typeof AuthenticatedMyPlansIndexRoute
  '/my-plans/$planId': typeof AuthenticatedMyPlansPlanIdLayoutRouteWithChildren
  '/my-plans/$planId/': typeof AuthenticatedMyPlansPlanIdIndexRoute
  '/profile/$userId/': typeof AuthenticatedProfileUserIdIndexRoute
  '/my-plans/$planId/bills/': typeof AuthenticatedMyPlansPlanIdLayoutBillsIndexRoute
  '/my-plans/$planId/config/': typeof AuthenticatedMyPlansPlanIdLayoutConfigIndexRoute
  '/my-plans/$planId/dashboard/': typeof AuthenticatedMyPlansPlanIdLayoutDashboardIndexRoute
  '/my-plans/$planId/members/': typeof AuthenticatedMyPlansPlanIdLayoutMembersIndexRoute
  '/my-plans/$planId/phases/': typeof AuthenticatedMyPlansPlanIdLayoutPhasesIndexRoute
  '/my-plans/$planId/phases/$phaseId/': typeof AuthenticatedMyPlansPlanIdLayoutPhasesPhaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/my-plans': typeof AuthenticatedMyPlansIndexRoute
  '/my-plans/$planId': typeof AuthenticatedMyPlansPlanIdIndexRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdIndexRoute
  '/my-plans/$planId/bills': typeof AuthenticatedMyPlansPlanIdLayoutBillsIndexRoute
  '/my-plans/$planId/config': typeof AuthenticatedMyPlansPlanIdLayoutConfigIndexRoute
  '/my-plans/$planId/dashboard': typeof AuthenticatedMyPlansPlanIdLayoutDashboardIndexRoute
  '/my-plans/$planId/members': typeof AuthenticatedMyPlansPlanIdLayoutMembersIndexRoute
  '/my-plans/$planId/phases': typeof AuthenticatedMyPlansPlanIdLayoutPhasesIndexRoute
  '/my-plans/$planId/phases/$phaseId': typeof AuthenticatedMyPlansPlanIdLayoutPhasesPhaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/my-plans/': typeof AuthenticatedMyPlansIndexRoute
  '/_authenticated/my-plans/$planId/_layout': typeof AuthenticatedMyPlansPlanIdLayoutRouteWithChildren
  '/_authenticated/my-plans/$planId/': typeof AuthenticatedMyPlansPlanIdIndexRoute
  '/_authenticated/profile/$userId/': typeof AuthenticatedProfileUserIdIndexRoute
  '/_authenticated/my-plans/$planId/_layout/bills/': typeof AuthenticatedMyPlansPlanIdLayoutBillsIndexRoute
  '/_authenticated/my-plans/$planId/_layout/config/': typeof AuthenticatedMyPlansPlanIdLayoutConfigIndexRoute
  '/_authenticated/my-plans/$planId/_layout/dashboard/': typeof AuthenticatedMyPlansPlanIdLayoutDashboardIndexRoute
  '/_authenticated/my-plans/$planId/_layout/members/': typeof AuthenticatedMyPlansPlanIdLayoutMembersIndexRoute
  '/_authenticated/my-plans/$planId/_layout/phases/': typeof AuthenticatedMyPlansPlanIdLayoutPhasesIndexRoute
  '/_authenticated/my-plans/$planId/_layout/phases/$phaseId/': typeof AuthenticatedMyPlansPlanIdLayoutPhasesPhaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/sign-up/'
    | '/verify/'
    | '/dashboard/'
    | '/my-plans/'
    | '/my-plans/$planId'
    | '/my-plans/$planId/'
    | '/profile/$userId/'
    | '/my-plans/$planId/bills/'
    | '/my-plans/$planId/config/'
    | '/my-plans/$planId/dashboard/'
    | '/my-plans/$planId/members/'
    | '/my-plans/$planId/phases/'
    | '/my-plans/$planId/phases/$phaseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/verify'
    | '/dashboard'
    | '/my-plans'
    | '/my-plans/$planId'
    | '/profile/$userId'
    | '/my-plans/$planId/bills'
    | '/my-plans/$planId/config'
    | '/my-plans/$planId/dashboard'
    | '/my-plans/$planId/members'
    | '/my-plans/$planId/phases'
    | '/my-plans/$planId/phases/$phaseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login/'
    | '/sign-up/'
    | '/verify/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/my-plans/'
    | '/_authenticated/my-plans/$planId/_layout'
    | '/_authenticated/my-plans/$planId/'
    | '/_authenticated/profile/$userId/'
    | '/_authenticated/my-plans/$planId/_layout/bills/'
    | '/_authenticated/my-plans/$planId/_layout/config/'
    | '/_authenticated/my-plans/$planId/_layout/dashboard/'
    | '/_authenticated/my-plans/$planId/_layout/members/'
    | '/_authenticated/my-plans/$planId/_layout/phases/'
    | '/_authenticated/my-plans/$planId/_layout/phases/$phaseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-plans/': {
      id: '/_authenticated/my-plans/'
      path: '/my-plans'
      fullPath: '/my-plans/'
      preLoaderRoute: typeof AuthenticatedMyPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$userId/': {
      id: '/_authenticated/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof AuthenticatedProfileUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-plans/$planId/': {
      id: '/_authenticated/my-plans/$planId/'
      path: '/my-plans/$planId'
      fullPath: '/my-plans/$planId/'
      preLoaderRoute: typeof AuthenticatedMyPlansPlanIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-plans/$planId/_layout': {
      id: '/_authenticated/my-plans/$planId/_layout'
      path: '/my-plans/$planId'
      fullPath: '/my-plans/$planId'
      preLoaderRoute: typeof AuthenticatedMyPlansPlanIdLayoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-plans/$planId/_layout/phases/': {
      id: '/_authenticated/my-plans/$planId/_layout/phases/'
      path: '/phases'
      fullPath: '/my-plans/$planId/phases/'
      preLoaderRoute: typeof AuthenticatedMyPlansPlanIdLayoutPhasesIndexRouteImport
      parentRoute: typeof AuthenticatedMyPlansPlanIdLayoutRoute
    }
    '/_authenticated/my-plans/$planId/_layout/members/': {
      id: '/_authenticated/my-plans/$planId/_layout/members/'
      path: '/members'
      fullPath: '/my-plans/$planId/members/'
      preLoaderRoute: typeof AuthenticatedMyPlansPlanIdLayoutMembersIndexRouteImport
      parentRoute: typeof AuthenticatedMyPlansPlanIdLayoutRoute
    }
    '/_authenticated/my-plans/$planId/_layout/dashboard/': {
      id: '/_authenticated/my-plans/$planId/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/my-plans/$planId/dashboard/'
      preLoaderRoute: typeof AuthenticatedMyPlansPlanIdLayoutDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedMyPlansPlanIdLayoutRoute
    }
    '/_authenticated/my-plans/$planId/_layout/config/': {
      id: '/_authenticated/my-plans/$planId/_layout/config/'
      path: '/config'
      fullPath: '/my-plans/$planId/config/'
      preLoaderRoute: typeof AuthenticatedMyPlansPlanIdLayoutConfigIndexRouteImport
      parentRoute: typeof AuthenticatedMyPlansPlanIdLayoutRoute
    }
    '/_authenticated/my-plans/$planId/_layout/bills/': {
      id: '/_authenticated/my-plans/$planId/_layout/bills/'
      path: '/bills'
      fullPath: '/my-plans/$planId/bills/'
      preLoaderRoute: typeof AuthenticatedMyPlansPlanIdLayoutBillsIndexRouteImport
      parentRoute: typeof AuthenticatedMyPlansPlanIdLayoutRoute
    }
    '/_authenticated/my-plans/$planId/_layout/phases/$phaseId/': {
      id: '/_authenticated/my-plans/$planId/_layout/phases/$phaseId/'
      path: '/phases/$phaseId'
      fullPath: '/my-plans/$planId/phases/$phaseId/'
      preLoaderRoute: typeof AuthenticatedMyPlansPlanIdLayoutPhasesPhaseIdIndexRouteImport
      parentRoute: typeof AuthenticatedMyPlansPlanIdLayoutRoute
    }
  }
}

interface AuthenticatedMyPlansPlanIdLayoutRouteChildren {
  AuthenticatedMyPlansPlanIdLayoutBillsIndexRoute: typeof AuthenticatedMyPlansPlanIdLayoutBillsIndexRoute
  AuthenticatedMyPlansPlanIdLayoutConfigIndexRoute: typeof AuthenticatedMyPlansPlanIdLayoutConfigIndexRoute
  AuthenticatedMyPlansPlanIdLayoutDashboardIndexRoute: typeof AuthenticatedMyPlansPlanIdLayoutDashboardIndexRoute
  AuthenticatedMyPlansPlanIdLayoutMembersIndexRoute: typeof AuthenticatedMyPlansPlanIdLayoutMembersIndexRoute
  AuthenticatedMyPlansPlanIdLayoutPhasesIndexRoute: typeof AuthenticatedMyPlansPlanIdLayoutPhasesIndexRoute
  AuthenticatedMyPlansPlanIdLayoutPhasesPhaseIdIndexRoute: typeof AuthenticatedMyPlansPlanIdLayoutPhasesPhaseIdIndexRoute
}

const AuthenticatedMyPlansPlanIdLayoutRouteChildren: AuthenticatedMyPlansPlanIdLayoutRouteChildren =
  {
    AuthenticatedMyPlansPlanIdLayoutBillsIndexRoute:
      AuthenticatedMyPlansPlanIdLayoutBillsIndexRoute,
    AuthenticatedMyPlansPlanIdLayoutConfigIndexRoute:
      AuthenticatedMyPlansPlanIdLayoutConfigIndexRoute,
    AuthenticatedMyPlansPlanIdLayoutDashboardIndexRoute:
      AuthenticatedMyPlansPlanIdLayoutDashboardIndexRoute,
    AuthenticatedMyPlansPlanIdLayoutMembersIndexRoute:
      AuthenticatedMyPlansPlanIdLayoutMembersIndexRoute,
    AuthenticatedMyPlansPlanIdLayoutPhasesIndexRoute:
      AuthenticatedMyPlansPlanIdLayoutPhasesIndexRoute,
    AuthenticatedMyPlansPlanIdLayoutPhasesPhaseIdIndexRoute:
      AuthenticatedMyPlansPlanIdLayoutPhasesPhaseIdIndexRoute,
  }

const AuthenticatedMyPlansPlanIdLayoutRouteWithChildren =
  AuthenticatedMyPlansPlanIdLayoutRoute._addFileChildren(
    AuthenticatedMyPlansPlanIdLayoutRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedMyPlansIndexRoute: typeof AuthenticatedMyPlansIndexRoute
  AuthenticatedMyPlansPlanIdLayoutRoute: typeof AuthenticatedMyPlansPlanIdLayoutRouteWithChildren
  AuthenticatedMyPlansPlanIdIndexRoute: typeof AuthenticatedMyPlansPlanIdIndexRoute
  AuthenticatedProfileUserIdIndexRoute: typeof AuthenticatedProfileUserIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedMyPlansIndexRoute: AuthenticatedMyPlansIndexRoute,
  AuthenticatedMyPlansPlanIdLayoutRoute:
    AuthenticatedMyPlansPlanIdLayoutRouteWithChildren,
  AuthenticatedMyPlansPlanIdIndexRoute: AuthenticatedMyPlansPlanIdIndexRoute,
  AuthenticatedProfileUserIdIndexRoute: AuthenticatedProfileUserIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
